# Generated by Django 4.2.3 on 2024-01-09 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinDisease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255)),
                ('disease_overview', models.TextField()),
                ('disease_symptoms', models.TextField()),
                ('disease_causeses', models.TextField()),
                ('disease_preventions', models.TextField()),
                ('disease_image1', models.ImageField(null=True, upload_to='disease_pics/')),
                ('disease_image2', models.ImageField(null=True, upload_to='disease_pics/')),
                ('disease_image3', models.ImageField(null=True, upload_to='disease_pics/')),
                ('disease_image4', models.ImageField(null=True, upload_to='disease_pics/')),
                ('disease_image5', models.ImageField(null=True, upload_to='disease_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='profile_pics/default.jpg', max_length=255, upload_to='profile_pics')),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectInfo',
            fields=[
                ('detect_id', models.AutoField(primary_key=True, serialize=False)),
                ('detect_date', models.DateTimeField()),
                ('detect_photo', models.ImageField(upload_to='detect_pics/')),
                ('detect_result', models.FileField(upload_to='detect_tex/')),
                ('detect_score', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skindisease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
