# Generated by Django 4.2.3 on 2024-02-19 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinDisease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255)),
                ('disease_overview', models.TextField(null=True)),
                ('disease_symptoms', models.TextField(null=True)),
                ('disease_causeses', models.TextField(null=True)),
                ('disease_preventions', models.TextField(null=True)),
                ('disease_images_folder', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', max_length=255, upload_to=users.models.profile_image_path)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectInfo',
            fields=[
                ('detect_id', models.AutoField(primary_key=True, serialize=False)),
                ('detect_date', models.DateTimeField()),
                ('detect_photo', models.ImageField(upload_to='detect_pics/')),
                ('detect_result', models.TextField(null=True)),
                ('detect_score', models.FloatField(null=True)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.skindisease')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
