# Generated by Django 4.2.7 on 2023-12-29 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinDisease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255)),
                ('disease_overview', models.TextField()),
                ('disease_symptoms', models.TextField()),
                ('disease_causeses', models.TextField()),
                ('disease_preventions', models.TextField()),
                ('disease_image1', models.ImageField(upload_to='disease_pics/')),
                ('disease_image2', models.ImageField(upload_to='disease_pics/')),
                ('disease_image3', models.ImageField(upload_to='disease_pics/')),
                ('disease_image4', models.ImageField(upload_to='disease_pics/')),
                ('disease_image5', models.ImageField(upload_to='disease_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='DetectInfo',
            fields=[
                ('detect_id', models.AutoField(primary_key=True, serialize=False)),
                ('detect_date', models.DateTimeField()),
                ('detect_photo', models.ImageField(upload_to='detect_pics/')),
                ('detect_result', models.FileField(upload_to='detect_tex/')),
                ('detect_score', models.FloatField()),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skindisease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
