# Generated by Django 4.2.3 on 2024-01-11 17:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to=users.models.profile_image_path),
        ),
    ]
