# Generated by Django 4.2.7 on 2023-12-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_disease_id_detectinfo_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skindisease',
            name='disease_image1',
            field=models.ImageField(null=True, upload_to='disease_pics/'),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='disease_image2',
            field=models.ImageField(null=True, upload_to='disease_pics/'),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='disease_image3',
            field=models.ImageField(null=True, upload_to='disease_pics/'),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='disease_image4',
            field=models.ImageField(null=True, upload_to='disease_pics/'),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='disease_image5',
            field=models.ImageField(null=True, upload_to='disease_pics/'),
        ),
    ]
