# Generated by Django 5.0.1 on 2024-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_detectinfo_detect_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectinfo',
            name='detect_result',
            field=models.CharField(max_length=255),
        ),
    ]
