# Generated by Django 4.2.3 on 2023-12-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_address_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('disease_overview', models.TextField()),
                ('disease_symptom', models.TextField()),
                ('disease_causes', models.TextField()),
                ('disease_prevention', models.TextField()),
            ],
        ),
    ]
