# Generated by Django 5.0.1 on 2024-01-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_detectinfo_detect_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skindisease',
            name='disease_image1',
        ),
        migrations.RemoveField(
            model_name='skindisease',
            name='disease_image2',
        ),
        migrations.RemoveField(
            model_name='skindisease',
            name='disease_image3',
        ),
        migrations.RemoveField(
            model_name='skindisease',
            name='disease_image4',
        ),
        migrations.RemoveField(
            model_name='skindisease',
            name='disease_image5',
        ),
        migrations.AddField(
            model_name='skindisease',
            name='disease_images_folder',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='disease_causeses',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='disease_overview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='disease_preventions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='disease_symptoms',
            field=models.TextField(null=True),
        ),
    ]
