# Generated by Django 4.2.3 on 2024-01-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_detectinfo_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectinfo',
            name='disease',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.skindisease'),
            preserve_default=False,
        ),
    ]
