# Generated by Django 4.2.3 on 2024-01-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_skindisease_disease_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectinfo',
            name='disease',
        ),
    ]
