# Generated by Django 4.2.3 on 2023-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profiles/default.jpg', max_length=255, upload_to='profiles'),
        ),
    ]
