# Generated by Django 5.0.2 on 2024-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_detectinfo_disease_alter_detectinfo_detect_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
